Extract out IdGeneratorBase and Add NonceGenerator
appform-io/ranger pull request #43
Opened 2024-09-23 19:19 UTC by CyberDrudge

2024-09-30 11:03 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/NonceGeneratorBase.java
> +    public synchronized void cleanUp() {
make methods that you don't want to be overridden as final in base class. Only allow controlled override

2024-09-30 11:33 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/NonceGeneratorBase.java
> +    protected IdValidationState validateId(final List<IdValidationConstraint> inConstraints, final Id id, final boolean skipGlobal) {
this should be final

2024-09-30 11:35 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/NonceGeneratorBase.java
> +    protected IdValidationState validateId(final List<IdValidationConstraint> inConstraints, final Id id, final boolean skipGlobal) {
move public before protected and then private

2024-09-30 11:37 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +                                : getREGISTERED_DOMAINS().get(res.getDomain()).getCollisionChecker();
this might throw npe, use getOrDefault(res.getDomain(), Domain.DEFAULT)

2024-09-30 11:39 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +                .onRetry(event -> {
This is supposed to be a listener. Performing mutations in this is a very bad idea

2024-09-30 11:40 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +        RETRYER = Failsafe.with(Collections.singletonList(RETRY_POLICY));
List.of()

2024-09-30 11:40 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +    private final FailsafeExecutor<GenerationResult> RETRYER;
follow basic coding conventions

2024-09-30 11:41 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +    public Optional<IdInfo> generateWithConstraints(final String namespace, final Domain domain, final boolean skipGlobal) {
Mark overrides with `@Override` everywhere

2024-09-30 11:43 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +                    return GenerationResult.builder()
The checks should happen here

2024-09-30 11:47 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +
The issue is this implementation leaves too much for the specialization to do. Essential stuff like constrain validations etc should all be done in the base class. The _only_ responsibility of any specialization of the base should be to generate the id and hand it over to the base. The retry, collision checks etc should all happen in the base. The only function that need to be implemented by the specialization should be to generate an id based on it's logic

2024-09-30 11:48 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +        RetryPolicy<GenerationResult> RETRY_POLICY = RetryPolicy.<GenerationResult>builder()
These things should all be moved to base. It needs to expose a very limited set of methods (one or two) to generate the id based on logic(random in this case)

2024-09-30 11:49 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +                .onRetry(event -> {
Also i think this is being done twice. Once here once in get() method

2024-09-30 11:51 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +    public DateTime getDateTimeFromTime(final long time) {
what is this method, why is this public and why is it placed below private methods?

2024-09-30 11:52 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/GenerationResult.java
> +@Builder
Remove builder here. All members should be populated.

2024-09-30 11:53 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/IdGenerator.java
> +    private static final IdGeneratorBase baseGenerator = new IdGeneratorBase(
Too many comments already Havent reviewed this or any further file after this,

2024-09-30 11:54 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +
Every other method should be marked as final in base

2024-10-21 07:55 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +    public static void initialize(int node) {
NodeId is static as it is determined after the class has been initialized.
Also all instances of `IdGeneratorBase` should have the same NodeId.

2024-11-04 07:07 UTC, r0goyal commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +public class IdGeneratorBase {
All methods in this class are final. Looks like this would be use case of composition than inheritance

2024-12-29 16:38 UTC, r0goyal commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +    public static void initialize(final int node) {
We can get rid of this and let the library initialise per instance of this class

2025-01-02 07:09 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/GenerationResult.java
> +public class GenerationResult {
Added

2025-01-02 07:09 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +    protected final DateTimeFormatter DATE_TIME_FORMATTER;
Updated

2025-02-14 09:08 UTC, santanusinha requested changes

2025-02-14 09:08 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/formatter/IdFormatters.java
> +    public Optional<Id> parse(final String idString) {
Remove this

2025-02-14 09:08 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +public abstract class IdGeneratorBase {
Why is this class abstract when there are no abstract functions and the constructor is public as well?

2025-02-14 09:08 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +    public void setNodeId(int nodeId) {
Why is this non-final?

2025-02-14 09:08 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/NonceGenerator.java
> +public abstract class NonceGenerator {
Add a protected constructor

2025-02-14 09:08 UTC, santanusinha commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/RandomNonceGenerator.java
> +    public NonceInfo generateWithConstraints(final IdGenerationInput request) {
Override annotation missing

2025-02-17 09:33 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/IdGenerator.java
> +        if(null != globalConstraints && !globalConstraints.isEmpty() ) {
We don't want to process global constraints if the list is empty.

2025-02-17 09:33 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +public abstract class IdGeneratorBase {
Made the constructor protected

2025-02-17 10:10 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/formatter/IdFormatters.java
> +    public Optional<Id> parse(final String idString) {
This will be used for parsing all IDs.

2025-02-17 10:12 UTC, r0goyal commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/formatter/IdFormatters.java
> +    public Optional<Id> parse(final String idString) {
This would be required. So there are two layers to parsing - 

1. To determine which formatter was used to generate this ID (in future plan is to add two digit unique identifier per formatter for this)
2. Once formatter is defined, individual formatters would be invoked to further parse all related metadata from the ID  


This method is only trying to identify  the formatter. Rest would be done by individual formatters. We can probably move this method to a new class (say IDParsers)

2025-02-19 05:10 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/nonce/NonceGenerator.java
> +public abstract class NonceGenerator {
Added

2025-02-19 05:10 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/generator/IdGeneratorBase.java
> +    public void setNodeId(int nodeId) {
Made it final

2025-02-19 05:10 UTC, CyberDrudge commented on ranger-discovery-bundle/src/main/java/io/appform/ranger/discovery/bundle/id/IdGenerator.java
> +                .build());
Done

2025-02-19 08:40 UTC, merged